### ISSUE TITLE
Quickstart Script

### ISSUE THREAD

**Issue by amayer5125** [TechLancaster/tl-website#28]
We need to add directions for the quickstart.php script to the README.md

**Comment by zachfedor** [comment]
not like you'd read it anyway... 

;)

**Comment by amayer5125** [comment]
I dont think this will be needed after we have access to an api but wasnt sure if we wanted to add it for now...
The reason I know its missing is because I did read it... after you told me there was something to read.

**Comment by zachfedor** [comment]
yeah, i was just messing with you

instead of messing with oauth junk and configuring the calendar, i might just post an example (however outdated) events.json file so that anyone can get a fully functioning page

**Comment by brewcore** [comment]
We've added events-example.json to the repo, so I am closing this for now.
