### ISSUE TITLE
Favicon is Yeoman 

### ISSUE THREAD

**Issue by jswhetstone** [TechLancaster/tl-website#30]
Favicon is Yeoman, should be TL logo.
![screen shot 2015-09-29 at 11 44 35 am](https://cloud.githubusercontent.com/assets/5463011/10169535/8731ad70-669f-11e5-80d4-13fe9a665f70.png)

**Comment by brewcore** [comment]
Must be a cache issue, there is no favicon on the server at the moment.  We do need to fix it.

**Comment by zachfedor** [comment]
Interesting. I don't have one at all on firefox.
![screen shot 2015-09-29 at 4 04 30 pm](https://cloud.githubusercontent.com/assets/11153782/10176613/d85edf50-66c3-11e5-9466-36d4d6b6205e.png)

**Comment by zachfedor** [comment]
and none on chrome.
![screen shot 2015-09-29 at 4 05 26 pm](https://cloud.githubusercontent.com/assets/11153782/10176635/f2a15334-66c3-11e5-9ce0-35ad66624501.png)

**Comment by amayer5125** [comment]
I have it in chrome.
Most likely a cache thing.

**Comment by zachfedor** [comment]
Although, now that you mention it, the old tech lancaster site used the yeoman icon. I bet you it's a caching thing. 

Once we get the new icon, I'll add a version to the end of the url and that should solve our problem. But we need an icon first...

**Comment by zachfedor** [comment]
this will be fixed in #34
