### ISSUE TITLE
Migrate to Symfony Framework

### ISSUE THREAD

**Issue by brewcore** [TechLancaster/tl-website#33]
I'm thinking that the easiest path to adding new features to the site will be to move to the Symfony framework.  It's basically a more full-featured version of Silex (in fact most of the libraries are the same, just a bunch more are added).

This would allow us to roll out small improvements and CMS-like features over time instead of taking a large amount of time to theme a CMS and adapt to it.

What do you guys think?

**Comment by zachfedor** [comment]
I like the idea of building it up piece by piece instead of front-loading a whole ton of theme work.If you think Symfony is the way to go, I'm all for it. Kind of amusing that we're breaking away from Silex right after an MVP launch, haha, but at least we won't have to do much to migrate.

**Comment by brewcore** [comment]
Cool. Don't think of it so much as breaking away from Silex, it's more like Silex = Symfony Light.  Under the hood the templating and core libraries are the same.

**Comment by brewcore** [comment]
Implemented in PR #36
